export const lightTheme = {
      background: '#f0f0f0',
      text: '#333',
      inputBorder: '#ccc',
      inputBackground: '#fff',
      buttonBackground: '#5cb85c',
      buttonText: '#fff',
      buttonHoverBackground: '#4cae4c',
      sentMessageBackground: '#dcf8c6',
      receivedMessageBackground: '#fff',
      conversationActiveBackground: '#e0e0e0',
      conversationHoverBackground: '#f0f0f0',
      buttonActiveBackground: '#4cae4c',
      buttonActiveText: '#fff',
    };

    export const darkTheme = {
      background: '#333',
      text: '#fff',
      inputBorder: '#555',
      inputBackground: '#444',
      buttonBackground: '#555',
      buttonText: '#fff',
      buttonHoverBackground: '#666',
      sentMessageBackground: '#444',
      receivedMessageBackground: '#555',
      conversationActiveBackground: '#666',
      conversationHoverBackground: '#777',
      buttonActiveBackground: '#666',
      buttonActiveText: '#fff',
    };

    export const brutalistTheme = {
      background: '#222',
      text: '#fff',
      inputBorder: '#000',
      inputBackground: '#333',
      buttonBackground: '#000',
      buttonText: '#fff',
      buttonHoverBackground: '#111',
      sentMessageBackground: '#333',
      receivedMessageBackground: '#444',
      conversationActiveBackground: '#111',
      conversationHoverBackground: '#222',
      buttonActiveBackground: '#111',
      buttonActiveText: '#fff',
    };

    export const skeuomorphicTheme = {
      background: '#e0e0d1',
      text: '#333',
      inputBorder: '#b3b3a3',
      inputBackground: '#f0f0e1',
      buttonBackground: '#c0c0b0',
      buttonText: '#333',
      buttonHoverBackground: '#d0d0c0',
      sentMessageBackground: '#d0e0c0',
      receivedMessageBackground: '#f0f0e1',
      conversationActiveBackground: '#d0d0c0',
      conversationHoverBackground: '#e0e0d1',
      buttonActiveBackground: '#d0d0c0',
      buttonActiveText: '#333',
    };

    export const glassmorphicTheme = {
      background: 'rgba(255, 255, 255, 0.1)',
      text: '#fff',
      inputBorder: 'rgba(255, 255, 255, 0.3)',
      inputBackground: 'rgba(255, 255, 255, 0.2)',
      buttonBackground: 'rgba(255, 255, 255, 0.3)',
      buttonText: '#fff',
      buttonHoverBackground: 'rgba(255, 255, 255, 0.4)',
      sentMessageBackground: 'rgba(255, 255, 255, 0.2)',
      receivedMessageBackground: 'rgba(255, 255, 255, 0.1)',
      conversationActiveBackground: 'rgba(255, 255, 255, 0.3)',
      conversationHoverBackground: 'rgba(255, 255, 255, 0.2)',
      buttonActiveBackground: 'rgba(255, 255, 255, 0.4)',
      buttonActiveText: '#fff',
    };
